### ISSUE TITLE
[quiz] Getting data

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#20]
Under which scenarios would you use each of the following?
- wget
- curl
- rsync
- scp

In otherwords they each have their own strengths.  What is each's strength?

**Comment by lisa418** [comment]
Wget - Command line program for downloading data from the web. Good for quickly downloading files via HTTP or FTP and scraping data from a webpage through its recursive feature.

Curl - Command line program for downloading data from the web. Can transfer files through more protocols than Wget including SFTP (secure FTP) and SCP (secure copy). Curl is also a library which means you can use it in R.

Rsync - Can synchronize an entire directory of data across a network. It's fast because it only sends differences between file versions and can compress files during transfers. It's also a good choice for network backups of entire directories due to archiving ability. 

scp - Can quickly copy a single file over a SSH (secure shell) connection instead of Rsync which can be overkill. Wget and Curl are web only and not designed to work on SSH.

**Comment by kubu4** [comment]
wget - Useful for downloading files from internet locations.  Can download recursively (to a fault, if one isn't careful).  Also allows downloading from password-protected sites.

curl - Similar to wget, but has added utility in being able to use SFTP and SCP.  Additionally, due to it's existence as a library (and not a command line program), curl can be incorporated/used within other computer programs, like R.

Rsync - As the name implies, it's useful for syncing files/folders across a network/remote server.  Like Git, it only tracks/transfers differences between files in locations, so it can be very fast to synchronize data.  Additionally, has an "archiving" option that will preserve metadata about files: time stamps, which user created/modified a file, read/write permissions.

scp - Secure copy is a form of SSH to copy (securely) file(s) from one location to another.  Although the author suggests that Rsync is overkill for single file transfers when compared to scp (despite the fact that implementing scp or Rsync is nearly identical), he neglects to explain why.

**Comment by jldimond** [comment]
All of these programs can be used to retrieve data over some kind of remote connection, but they are all a bit different.

Wget and curl are best for downloading large files from the internet that your browser can't handle. Wget is good for downloading data over HTTP or FTP, and has a recursive function that can allow it to download multiple files from a site (this is a powerful feature, so you must use care). Curl is similar, but best when downloading files over a secure connection like SFTP or SCP. It can be used within other programs like R.

Rsync and secure copy (scp) are tools used to transfer files over an SSH connection. Rsync is the more powerful tool of the two and can be used, for example, to synchronize large directories over SSH. It is good at keeping track of changes and only modifying files when there are differences. If you only need to transfer a single file over SSH, Rsync is a bit overkill and in that case you are better off using scp

**Comment by jheare** [comment]
wget and curl are essentially the same as both assist in downloading information via the command line.  

rsync helps synchronize files across a network to ensure all working copies are of the same version on the network. 

scp is a tool to download information from a remote machine while tunneling into it using SSH. This can allow for you to process data on much faster machines but still retain a local copy of the outputs for local analysis.

**Comment by willking2** [comment]
download from the internet
- wget
  - can download data recursively (download data on the page as well as the data in the links the page contains, for 5 links "deep")
  - download via HTTP or FTP
- curl
  - can do download via SFTP, SCP (as opposed to curl)
  - is a library, so can be used in other things like R (whoa)

biiiig data transfers
- rsync
  - fast b/c syncs differences, can compress
  - good backup and archiving system
- scp
  - if you want to copy a file while working in SSH (like cp in unix, but secure)

**Comment by jheare** [comment]
[Here](https://kb.iu.edu/d/agye) is a fun walkthrough on how to use SCP, just incase anyone was wondering.
