### ISSUE TITLE
[quiz] Standard Error

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#28]
What is standard error? How might you monitor it? Why would you monitor it?

**Comment by jldimond** [comment]
Standard error refers to error messages and warnings. By default it is displayed to the terminal, but you can also monitor it by redirecting it to a file that will act as a log of the standard error. This helps you keep track of errors and warnings in your output.

**Comment by kubu4** [comment]
Standard error is one of the three data streams available in Unix programs.  It can be monitored by redirecting the standard error stream (by using the '2>' designation) to an output file.  To monitor the stream in real time, one can use the the command:

```
$tail -f stderr.txt
```

This will continuously print the the last (i.e. newest) lines of the stderr.txt file to the terminal.

Monitoring this is useful if the standard error stream outputs important messages that might otherwise be missed, especially if the error isn't fatal (i.e. doesn't cause the program to terminate.) which would alert the user that problem occurred.

**Comment by jheare** [comment]
Typical error message produced by scripts and programs are considered standard error. These messages typically appear as comments inline in the terminal window but do not print in the standard output stream which is reserved for data outputs. To print these messages to a log, a user must designate a second stream with 2> to send the message to a designated error log file. You should monitor these messages because they often contain useful information about problems occurring during a programs run that would not be noticed otherwise.

**Comment by willking2** [comment]
What is standard error?
A message from the program tell you that something's up -- "errors, warnings, and messages" for the user to read.

How might you monitor it? 
It usually comes out in the terminal, so you can read it there. You can redirect it to an output file if it's important, or even redirect it to a 'blackhole' (into a psuedo device) so that you never even have to see it or save it. 

Why would you monitor it?
- check your errors and messages 
- let your collaborators check your standard errors (like to help debug)

**Comment by lisa418** [comment]
Standard error is a stream for errors, warning and messages in the Unix shell that should be read to avoid files being corrupted. This can be especially problematic when copying and pasting large files from memory. Standard error is by default directed to your terminal or you can redirect this stream to an error log using the command 2>.
