### ISSUE TITLE
[quiz] What the grep?

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#29]
Please explain what the following code does.

```
grep -v "^>" tb1.fasta | \
grep --color -i "[^ATCG]"
```

**Comment by jldimond** [comment]
The first line removes the header symbol ">" from the FASTA file, then connects to the next line of code with a pipe and a backslash. The second line looks for any character in the FASTA that is not an A, T, C, or G and colors it so it can be easily spotted. The -i makes the search case insensitive. 

This brings up a question I have. In some FASTAs I have seen characters other than ATCG (usually an N or M). First, what are these? And second, do these make a difference in the analysis I am doing, or should I be getting rid of them?

**Comment by sr320** [comment]
See page 46 in this week's reading. :disappointed: 
and page 325.

Does not make any difference.

**Comment by jldimond** [comment]
Is this one of those classes where there's no such thing as a dumb question? :grinning:

Here's a list of all those ambiguous nucleotides I found:

![untitled](https://cloud.githubusercontent.com/assets/9869457/6067121/0e7a077e-ad27-11e4-9e71-44bae9c95891.png)

**Comment by kubu4** [comment]
The first part of the grep command identifies all lines in the tb1.fasta file that do <em>not</em> begin with a greater-than symbol.  The output from this gets piped to the next grep command.  The next grep command prints all characters to the terminal screen that do <em>not</em> match A, C, T, or G (upper or lower case)and colors the output.

**Comment by sr320** [comment]
@jldimond take a look at @kubu4 's answer - (this is a solution to not changing contig name to avoid CG counts)

**Comment by jheare** [comment]
The first half of the code before the \ searches the fasta file for lines that do not begin with the quoted text. -v indicates an inversion in the search so unlike standard grep which would just search for the quoted text, the -v tells grep to look for things that are not like the quoted text. The \ is just an identifier that tells the command line the script continues on the next line. The second half of the script tells grep to print out anything that doesn't match the quoted text. The quoted text it self acts as a repository of all objects that grep needs to ignore based on the -i command, the brackets and ^ indicate that each character should be ignored in the search. The --color command tells grep to print matching cases in color so that its easier to see which lines do not match.

**Comment by willking2** [comment]
```
grep -v "^>" tb1.fasta | \
```

Removes header lines: finds all lines starting with ">", but -v makes it inverted (exclude lines starting with ">").

The "|" is the pipe, telling unix to take output from the first grep and make it the input into the next grep. The "\" just means that the code is in the same line, but it's separated for readability. 

```
grep --color -i "[^ATCG]"
```

Now we're finding characters that aren't A, T, C, or G. the "-i" means to ignore upper/lower case. "--color" will color anything that's not A, T, C, or G. 

one thing to note is that "^" can mean to start search from beginning of the line (first case) or to exclude something  (second case).

**Comment by lisa418** [comment]
-v "^>" finds all lines in the file "tb1.fasta" that do not begin with a > and transfers or pipes only those lines to the next command which displays and color codes (for easy visibility) any characters that do not match "[^ATCG]"
