### ISSUE TITLE
[quiz] Remote access

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#30]
Based on this weeks reading - what procedure would you use to remote into hummingbird to carry out a blastx job.

Specifically what exact commands / scripts would you use. Lets pretend the ip address is 029.32.233.40 and the username is `grenich` and password `8e3d`.

**Comment by jldimond** [comment]
To make it easy for a remote that you use often, create a config file located at ~/.ssh/config.

$ cd .ssh
$ nano config  #creates text file named config using nano

#enter into text file:

hummingbird
HostName 029.32.233.40 
User grenich
Port 8000

#now you login by typing:

$ssh hummingbird

#then you'll be prompted for password

**Comment by kubu4** [comment]
```
$ssh grenich@029.32.233.40
Password: 8e3d
hummingbird:~grenich$blastx -query BioinformaticsTools/ncbi-blast-2.2.29+/queries/contigs.fa \
-db contigs -outfmt 6 -max_target_seqs 1 -num_threads 16 -out /BioinformaticsTools/ncbi-blast-2.2.29+/outputs/BlastxContigs.txt
```

**Comment by jheare** [comment]
The reading suggests using SSH to login to a remote server. As a windows user, I find using a program such as PuTTY easier to manage ssh connections because I'm also able to create tunnels which is useful for ipython notebook. What I would do is enter in the IP address to PuTTY SSH IP field and label the ip address as hummingbird. You can see what this would look like [here](http://eagle.fish.washington.edu/dermochelys/puttypics.jpg). Then I would use PuTTY to connect to the server and when prompted I would apply the username and password.

**Comment by willking2** [comment]
```
$cd .ssh/config
Host hummingbird
HostName  029.32.233.40 
User grenich
Port 7001

$ssh hummingbird
password: 8e3d
```

**Comment by lisa418** [comment]
#create an SSH config file
$ cd .ssh/config
#file should have the following info
Host hummingbird
HostName  029.32.233.40 
User grenich
Port # (default 22)
#log in to hummingbird
$ssh hummingbird
password: 8e3d
#blast away!
blastx \
-query {fa} \
-db {db} \
-max_target_seqs 1 \
-max_hsps 1 \
-outfmt 6 \
-evalue 1E-05 \
-num_threads 6 \
-out ../analyses/{sp}_sprot.tab
