### ISSUE TITLE
MySQL on Hummingbird

### ISSUE THREAD

**Issue by jheare** [sr320/fish546-2015#45]
Hey Guys, 

I'm trying to look through my data to find interesting things about SNPS and alleles but I'm having trouble figuring out how to produce the information. STACKS has a wonderful output into MySQL but I don't know how to access it via remote/tunneling. I've also tried to export the summary information using the built in export_sql.pl function in STACKS but that also has problems as there appears to be a missing library in hummingbird to produce TSV and XLS files. My notebook also failed to save for some reason but I took a [screen shot of the error](http://eagle.fish.washington.edu/dermochelys/exportsqlerror.jpg). Does anyone know how to produce summary files for STACKS that I can actually view to get information about SNPs, Loci, and Alleles.

**Comment by kubu4** [comment]
OS X has sqlite3 installed on it by default (sqlite3.7.15.1).  Will that work for handling the sql file(s)?

Your other error was generated because the WriteExcel module for Perl was not installed.  I installed both the WriteExcel and ParseExcel (just in case) modules.  Give your command another rip and see what happens.  I'm not entirely sure if the installation of these modules is global or just for my user.  Also, I had to install them using `sudo`, so if you run your command and it doesn't work, try running the command with `sudo` and see if it'll run that way.

**Comment by kubu4** [comment]
Steps I took to install WriteExcel.pm and ParseExcel.pm (perl modules) on Hummingbird (srlab account):
`$cd /usr/local/lib`
`$sudo perl -e'use CPAN; install "Spreadsheet::WriteExcel"'`
`sudo perl -e'use CPAN; install "Spreadsheet::ParseExcel"'`

Verify installation:
`$ ls -l /Library/Perl/5.16/Spreadsheet`

```
total 672
drwxr-xr-x  15 root  wheel     510 Feb 13 20:52 ParseExcel
-r-xr-xr-x   1 root  wheel  115063 Mar 18  2014 ParseExcel.pm
drwxr-xr-x  14 root  wheel     476 Feb 13 20:52 WriteExcel
-r--r--r--   1 root  wheel  224816 Nov  6  2013 WriteExcel.pm
```

Add execute permissions to `WriteExcel.pm` Perl module:
`sudo chmod +x WriteExcel.pm`

Verify permission change:
`$ ls -l /Library/Perl/5.16/Spreadsheet`

```
total 672
drwxr-xr-x  15 root  wheel     510 Feb 13 20:52 ParseExcel
-r-xr-xr-x   1 root  wheel  115063 Mar 18  2014 ParseExcel.pm
drwxr-xr-x  14 root  wheel     476 Feb 13 20:52 WriteExcel
-r-xr-xr-x   1 root  wheel  224816 Nov  6  2013 WriteExcel.pm
```

**Comment by jheare** [comment]
Awesome! Thanks Sam. When I get a chance I'll try out the sqltoexcel code
for stacks!
