### ISSUE TITLE
[quiz] Needs most improvement

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#50]
What aspect of your draft product could use the most improvement? 
Why?

**Comment by willking2** [comment]
Quick fix: make datarecords.md more organized and easier to read 
Needs improvement: make stress specific products (tables and figures), expand more on stress in background. This will make link the project more directly to my research interests.

**Comment by lisa418** [comment]
My data records section needs the most improvement. I need to work on organizing my current files on GitHub and generating files for DESeq2 analysis and beyond.

**Comment by jldimond** [comment]
I'm close to having my workflow the way I want it, so that's (hopefully) not a huge thing. The elephant in the room is definitely the acquisition and analysis of the other 90% of the data I have said that I'm going to analyze.

**Comment by jheare** [comment]
I need to write an actually narrative with explanations of each data file.  I also need to include more information about each file as pulled from the standard error logs. This will improve the value of each file while improving the clarity of the file structure to the reader.

**Comment by kubu4** [comment]
The biggest "improvement" is that I need to figure out how to proceed next with the gene expression differences and annotations. So, the improvement would be actually progressing to the next aspect of the project. I need to implement this improvement because without figuring out the next step, I won't have a "product" that conveys any useful information.
